# Generated by Django 5.2 on 2026-09-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0004_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='monitoringapp.announcement')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_recipients', to='monitoringapp.user')),
            ],
            options={
                'ordering': ['-announcement__created_at'],
                'unique_together': {('announcement', 'recipient')},
            },
        ),
    ]
