# Generated by Django 5.2 on 2026-09-24 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0005_announcementrecipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttimesetting',
            options={'ordering': ['day_of_week', 'report_type']},
        ),
        migrations.AddField(
            model_name='reporttimesetting',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='reporttimesetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reporttimesetting',
            name='team_lead',
            field=models.ForeignKey(blank=True, limit_choices_to={'job_Position__iexact': 'Team Lead'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_time_settings', to='monitoringapp.user'),
        ),
        migrations.AlterField(
            model_name='reporttimesetting',
            name='report_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reporttimesetting',
            unique_together={('team_lead', 'day_of_week', 'report_type')},
        ),
    ]
