# Generated by Django 5.2 on 2026-09-24 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0006_alter_reporttimesetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('meeting_link', models.URLField()),
                ('purpose', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_google_meetings', to='monitoringapp.user')),
                ('participants', models.ManyToManyField(blank=True, related_name='google_meetings', to='monitoringapp.user')),
            ],
        ),
    ]
