# Generated by Django 5.2 on 2026-09-28 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0007_googlemeeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamReportLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_leave', models.BooleanField(default=False)),
                ('evening_leave', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_report_leaves', to='monitoringapp.user')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('team_lead', 'date'), name='unique_team_report_leave_date')],
            },
        ),
    ]
