# Generated by Django 5.2 on 2026-09-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0008_teamreportleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('event_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamlead_notifications', to='monitoringapp.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
