# Generated by Django 5.2 on 2026-09-29 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0009_teamleadnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_report_schedules', to='monitoringapp.user')),
            ],
            options={
                'ordering': ['date', 'report_type'],
                'constraints': [models.UniqueConstraint(fields=('team_lead', 'date', 'report_type'), name='unique_team_lead_date_report_type')],
            },
        ),
    ]
