# Generated by Django 5.2 on 2026-09-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0010_reportdateschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefaultSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('day_kind', models.CharField(choices=[('regular', 'Regular days'), ('saturday', 'Saturday')], default='regular', max_length=10)),
                ('report_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_report_schedules', to='monitoringapp.user')),
            ],
            options={
                'ordering': ['effective_from', 'day_kind', 'report_type'],
                'constraints': [models.UniqueConstraint(fields=('team_lead', 'effective_from', 'day_kind', 'report_type'), name='unique_default_report_schedule')],
            },
        ),
    ]
