# Generated by Django 5.2 on 2026-09-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0011_reportdefaultschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleadnotification',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
