# Generated by Django 5.2 on 2026-09-30 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0012_teamleadnotification_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeadReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('event_at', models.DateTimeField(db_index=True)),
                ('remind_at', models.DateTimeField(db_index=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder', to='monitoringapp.teamleadnotification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamlead_reminders', to='monitoringapp.user')),
            ],
            options={
                'ordering': ['event_at', 'id'],
            },
        ),
    ]
