# Generated by Django 5.2 on 2026-10-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0013_teamleadreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='deleted_for_everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_hidden_messages', to='monitoringapp.user'),
        ),
    ]
