# Generated by Django 5.2 on 2026-10-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_deleted_for_everyone_and_more'),
        ('monitoringapp', '0014_groupmessage_deleted_for_everyone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_id', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chat.conversation')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='monitoringapp.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to='monitoringapp.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'conversation'), name='unique_user_conversation_read'), models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group_read'), models.CheckConstraint(condition=models.Q(models.Q(('conversation__isnull', False), ('group__isnull', True)), models.Q(('conversation__isnull', True), ('group__isnull', False)), _connector='OR'), name='chat_read_exactly_one_target')],
            },
        ),
    ]
