# Generated by Django 5.2 on 2026-10-06 06:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0015_chatreadstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_income_entries', to='monitoringapp.user')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='accounts_income_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='accounts_income_amount_gt_zero')],
            },
        ),
    ]
