# Generated by Django 5.2 on 2026-10-06 09:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0017_accountsexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('customer_name', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_sales_entries', to='monitoringapp.user')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='accounts_sale_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='accounts_sale_amount_gt_zero'), models.CheckConstraint(condition=models.Q(('received_amount__gte', 0)), name='accounts_sale_received_gte_zero'), models.CheckConstraint(condition=models.Q(('received_amount__lte', models.F('amount'))), name='accounts_sale_received_lte_amt')],
            },
        ),
    ]
