# Generated by Django 5.2 on 2026-10-06 11:43

import django.core.validators
import django.db.models.deletion
import monitoringapp.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0018_accountssale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsExpenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.PositiveBigIntegerField()),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='accountsexpense',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='accountsexpense',
            name='receipt',
            field=models.FileField(blank=True, storage=monitoringapp.models.ExpenseReceiptStorage(), upload_to=monitoringapp.models.expense_receipt_upload_path),
        ),
        migrations.AddConstraint(
            model_name='accountsexpense',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__isnull', True), models.Q(('paid_amount__gte', 0), ('paid_amount__lte', models.F('amount'))), _connector='OR'), name='expense_paid_amount_valid'),
        ),
        migrations.AddField(
            model_name='accountsexpensehistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_history_actions', to='monitoringapp.user'),
        ),
        migrations.AddField(
            model_name='accountsexpensehistory',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='monitoringapp.accountsexpense'),
        ),
    ]
