# Generated by Django 5.2 on 2026-10-06 12:07

import django.db.models.deletion
import monitoringapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0019_accountsexpensehistory_accountsexpense_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsincome',
            name='receipt',
            field=models.FileField(blank=True, storage=monitoringapp.models.IncomeReceiptStorage(), upload_to=monitoringapp.models.income_receipt_upload_path),
        ),
        migrations.CreateModel(
            name='AccountsIncomeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_number', models.PositiveBigIntegerField()),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_history_actions', to='monitoringapp.user')),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='monitoringapp.accountsincome')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
