# Generated by Django 5.2 on 2026-10-06 12:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import monitoringapp.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0020_accountsincome_receipt_accountsincomehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountssale',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountssale',
            name='invoice_file',
            field=models.FileField(blank=True, storage=monitoringapp.models.SalesInvoiceStorage(), upload_to=monitoringapp.models.sales_invoice_upload_path),
        ),
        migrations.CreateModel(
            name='AccountsSalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True)),
                ('request_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_sale_payments', to='monitoringapp.user')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='monitoringapp.accountssale')),
            ],
            options={
                'ordering': ['-date', '-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sale_payment_amount_positive')],
            },
        ),
    ]
