# Generated by Django 5.2 on 2026-10-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0021_accountssale_due_date_accountssale_invoice_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('sale', 'Sale'), ('payment', 'Payment'), ('reminder', 'Reminder')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('event_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_notification_actions', to='monitoringapp.user')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_notifications', to='monitoringapp.user')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_archived', 'is_read', '-created_at'], name='acct_notif_inbox_idx')],
            },
        ),
    ]
